# Generated by Django 6.0.4 on 2026-04-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(max_length=200)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('capa_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
