# Generated by Django 6.0.4 on 2026-09-28 22:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_musica_enviado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Naipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='musica',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='letra_cifra',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='tom',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='FaixaAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='faixas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas', to='cadastro.musica')),
                ('naipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.naipe')),
            ],
            options={
                'ordering': ['naipe__ordem'],
                'unique_together': {('musica', 'naipe')},
            },
        ),
    ]
