# Generated by Django 6.0.4 on 2026-09-28 23:16

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_naipe_musica_criado_em_musica_letra_cifra_musica_tom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixaaudio',
            name='audio',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='faixas/'),
        ),
    ]
